name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - run: go version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Examine source code
        run: go vet -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        if: github.event_name == 'push'
        env:
          TEST_ENV_URL: ${{ secrets.TEST_ENV_URL }}
          TEST_INDEX_HTML_URL: ${{ secrets.TEST_INDEX_HTML_URL }}
          TEST_SENTRY_DSN: ${{ secrets.TEST_SENTRY_DSN }}
        run: go test -v -cover -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        if: github.event_name == 'push'
        run: bash <(curl -s https://codecov.io/bash)

      - name: Update Go report card
        if: github.event_name == 'push'
        uses: creekorful/goreportcard-action@v1.0
